# Generated by Django 5.1.2 on 2024-11-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text='Обязательное поле для заполнения', max_length=250, unique=True, verbose_name='Адрес электронной почты'),
        ),
    ]
